server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: metabase-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: "metabase-logs"
          __path__: /var/log/metabase/*.log

  - job_name: postgres-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: "postgres-logs"
          __path__: /var/log/postgresql/*.log

  - job_name: nginx-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: "nginx-logs"
          __path__: /var/tmp/nginx/*.log
