version: '3.8'

networks:
  app-network:

services:
  postgres:
    image: postgres:15.4
    ports:
      - "5452:5432"
    env_file:
      - ./postgres/.env
    command:
      - postgres
      - -c
      - logging_collector=on
      - -c
      - log_statement=all
      - -c
      - log_directory=/var/log/postgresql
      - -c
      - log_filename=postgresql.log
    volumes:
      - ./postgres/logs:/var/log/postgresql
    networks:
      - app-network
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1024M
    #       cpus: "1.0"

  metabase:
    build:
      context: ./metabase
    platform: linux/amd64
    ports:
      - "5050:3000"
    depends_on:
      - postgres15
    env_file:
      - ./metabase/.env
    volumes:
      - ./metabase/logs:/path/to/metabase/logs
    networks:
      - app-network
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1024M
    #       cpus: "1.0"

  loki:
    build:
      context: ./loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/data:/loki
    networks:
      - app-network
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1024M
    #       cpus: "1.0"

  promtail:
    image: grafana/promtail:2.7.1
    ports:
      - "9080:9080"
    volumes:
      - ./promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - ./postgres/logs:/var/log/postgresql
      - ./metabase/logs:/path/to/metabase/logs
      - /var/tmp/nginx:/var/tmp/nginx
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - app-network
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1024M
    #       cpus: "1.0"

  grafana:
    image: grafana/grafana:9.1.6
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - app-network
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1024M
    #       cpus: "1.0"

  nginx:
    build:
      context: ./nginx
    ports:
      - "8090:8090"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/tmp/nginx:/var/tmp/nginx
    networks:
      - app-network
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1024M
    #       cpus: "1.0"

volumes:
  grafana-storage:
